### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by portaloffreedom** [TheSamsai/Castawesome#1]
Is it possible to add in the settings also 
- audio quality (now only 128k)
- audio codec (now only mp3)
- video codec (now only x264)
- video container (now only flv)

**Comment by TheSamsai** [comment]
Castawesome was primarily developed as a livestreaming tool for Twitch etc. so these options (apart from the audio bitrate which I probably should have thought of) weren't something you'd typically change. But I think I could mess around and see if I can add an "advanced settings" thing somehow. Audio bitrate will probably be added to the general settings.

**Comment by xros** [comment]
Options for audio capturing devices? Microphone, USB webcam/microphone options?

B.T.W. I could not hear voice when streaming on twitch. Yet have not figured out how to set that.

**Comment by TheSamsai** [comment]
I doubt audio device selection will be implemented. For now the best way to do it is to open pavucontrol and select the capture device there. If you want both mic and PC audio at the same time you need to do some Pulseaudio magic according to these instructions: http://www.maartenbaert.be/simplescreenrecorder/recording-game-audio/

**Comment by TheSamsai** [comment]
Well, I had the vcodec, acodec, container stuff nearly sorted but all of that stuff got destroyed in a merge operation because I was dumb and made my changes to a release version instead of the dev version. Whole thing will be delayed.

**Comment by TheSamsai** [comment]
Okay, I decided to marathon it and rewrote the code. The support for video containers, codecs and audio bitrate is now in the 0.15.2 version. Container and codec settings are hidden by default and I recommend not messing with them unless you absolutely know what you are doing. Because they are text entries you can add just complete nonsense in there and break everything.
