### ISSUE TITLE
Interface redesign

### ISSUE THREAD

**Issue by maxolasersquad** [TheSamsai/Castawesome#16]
I would like to propose some interface redesign ideas that I've been throwing around in my head.

**Comment by maxolasersquad** [comment]
Here is a glade file that I threw together real quick. It just reimagines the current interface as a single tabbed interface. I have some more stuff I would like to do that is the purpose of the redesign that I just haven't had time to put together. I'll have that in the future. Let me know what you think of this direction.
[castawesome.glade.zip](https://github.com/TheSamsai/Castawesome/files/73223/castawesome.glade.zip)

**Comment by TheSamsai** [comment]
That looks good. Someone recommended that I make the UI tabbed but back then I had no idea how to go about doing that. The tabbed design is definitely a lot cleaner than the current multi-window approach.

**Comment by maxolasersquad** [comment]
I'm glad you like it. I'll keep toying with it before translating the glade to .ui and wiring up the functions.

**Comment by maxolasersquad** [comment]
I created a branch in my repository to keep track of the work.
https://github.com/maxolasersquad/Castawesome/tree/ui_redesign

I have made some further improvements to the UI. I will probably add just a few more tweeks and then start doing the actual work to make it a reality, if everything is agreeable.

**Comment by maxolasersquad** [comment]
I have finished my redesign proposals. Please take a look at the .glade file in my branch listed above and let me know what you think.

**Comment by maxolasersquad** [comment]
Finally got this wrapped it up.
