### ISSUE TITLE
Audio de-syncs after 10+ minutes

### ISSUE THREAD

**Issue by calexil** [TheSamsai/Castawesome#5]
as the title states, the audio of the stream de-syncs after streaming for any extended amount of time, this is not a problem for most games, but for rhythm games like stepmania, osu!, etc . It is vitally important that the audio stays in sync, otherwise the stream will be garbage. The only work around I have come up with is to turn the stream off then back on for every song...which is seriously sub-optimal cause it means the viewer has to refresh constantly, or sit through lots of loading screens

**Comment by maxolasersquad** [comment]
I think that [this stack exchange answer](https://askubuntu.com/questions/227497/avconv-ac3-to-aac-or-mp3-is-not-synced-with-video) is probably the key. I will do some testing to find out.

**Comment by calexil** [comment]
resolved by using obs instead ;)

**Comment by calexil** [comment]
closed project
